/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface Tracks {
  album: string | null;
  artists: Json | null;
  disc_number: number | null;
  duration_ms: number | null;
  ean: string | null;
  explicit: boolean | null;
  href: string | null;
  id: string;
  isrc: string | null;
  name: string;
  popularity: number | null;
  track_number: number | null;
  upc: string | null;
  uri: string | null;
}

export interface DB {
  tracks: Tracks;
}
