/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export type AlbumType = "album" | "compilation" | "single";

export interface Albums {
  artists: string[] | null;
  href: string | null;
  id: string;
  name: string;
  total_tracks: number | null;
  type: AlbumType;
  uri: string | null;
}

export interface Artists {
  genres: string[] | null;
  href: string | null;
  id: string;
  name: string;
  uri: string | null;
}

export interface Playlists {
  id: string;
  name: string;
  tracks: string[] | null;
}

export interface Tracks {
  album: string | null;
  artists: string[] | null;
  disc_number: number | null;
  duration_ms: number | null;
  explicit: boolean | null;
  href: string | null;
  id: string;
  name: string;
  popularity: number | null;
  track_number: number | null;
  uri: string | null;
}

export interface DB {
  albums: Albums;
  artists: Artists;
  playlists: Playlists;
  tracks: Tracks;
}
