/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AlbumType = "album" | "compilation" | "single";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type QueryType = "category" | "genre";

export type SpotifyEntityType = "album" | "artist" | "category" | "genre" | "playlist" | "track";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Albums {
  artist_ids: string[];
  id: string;
  label: string;
  name: string;
  popularity: number;
  release_date: string;
  total_tracks: number;
  type: AlbumType;
}

export interface Artists {
  followers: number | null;
  genres: string[];
  id: string;
  name: string;
  popularity: number | null;
}

export interface Categories {
  category: string;
}

export interface ErrIds {
  id: string;
  type: SpotifyEntityType;
}

export interface Genres {
  genre: string;
}

export interface Ids {
  id: string;
  type: SpotifyEntityType;
}

export interface PagedAlbums {
  id: string;
  paged: Json;
}

export interface Playlists {
  id: string;
  name: string;
  tracks: string[];
}

export interface SearchQueries {
  last_searched_at: Timestamp | null;
  query: string;
  type: QueryType;
}

export interface TokenEvents {
  client_id: string;
  details: string | null;
  event_type: string;
  id: Generated<number>;
  timestamp: Timestamp;
  used: number | null;
}

export interface Tracks {
  album_id: string | null;
  artist_ids: string[];
  disc_number: number | null;
  duration_ms: number | null;
  explicit: boolean | null;
  id: string;
  name: string;
  popularity: number | null;
  track_number: number | null;
}

export interface DB {
  albums: Albums;
  artists: Artists;
  categories: Categories;
  err_ids: ErrIds;
  genres: Genres;
  ids: Ids;
  paged_albums: PagedAlbums;
  playlists: Playlists;
  search_queries: SearchQueries;
  token_events: TokenEvents;
  tracks: Tracks;
}
